videobridge {
  ice {
    udp {
      port = 10000
    }
  }

  octo {
    enabled = true
    region = "in"
    relay-id = "in1"
    bind-address = "0.0.0.0"
    bind-port = 4096
    public-address = "13.200.180.164" 
  }
}
