jicofo {
  octo {
    enabled = true
    allow-multiple-bridges = true
  }

  bridge {
    selection-strategy = "RegionBasedBridgeSelectionStrategy"
    local-region = "eu"
    strict-region-matching = false
  }
  
conference {
    
    initial-timeout = 120000
    max-session-lifetime = 3600000
   
  }

  logging {
    level = DEBUG
  }
}
