jicofo {
  authentication {
    jwt {
      region-claim = "region"

    }
  }
  octo {
    enabled = true
  }

  bridge {
    selection-strategy = org.jitsi.jicofo.bridge.RegionBasedBridgeSelectionStrategy
  }
}
