# Enable the telnet admin interface
org.jitsi.jicofo.admin.ENABLE=true
org.jitsi.jicofo.admin.PORT=2222
org.jitsi.jicofo.admin.SECRET=secret123
# Region-based bridge selection
# Region-based bridge selection

# This line is **required** for RegionAwareBridgeSelectionStrat
org.jitsi.jicofo.BridgeSelectionStrategy.IGNORE_STRESS=true
org.jitsi.jicofo.BridgeSelector.BRIDGE_SELECTION_STRATEGY=RegionBasedBridgeSelectionStrategy
org.jitsi.jicofo.BridgeSelector.ALLOW_MULTIPLE_REGIONS=true
#org.jitsi.jicofo.auth.DISABLE_AUTO_EXPIRY=true
